apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Route
  metadata:
    name: snowstorm
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: snowstorm
- apiVersion: v1
  kind: Service
  metadata:
    name: snowstorm
  spec:
    selector:
      app: snowstorm
    ports:
    - port: 80
      targetPort: 8080
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: snowstorm
    labels:
      app: snowstorm
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: snowstorm
      spec:
        containers:
        - name: snowstorm
          image: snowstorm:latest
          ports:
            - name: http
              containerPort: 8080
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - snowstorm
        from:
          kind: ImageStreamTag
          name: snowstorm:latest
      type: ImageChange
